version: '3'
services:
  electrum:
    build:
      context: ./electrum
      args:
        ELECTRUM_VERSION: 3.2.3
        ELECTRUM_USER: electrum
        ELECTRUM_PASSWORD: changeme
    ports:
      - 127.0.0.1:7000:7000
    volumes:
      - /c/Users/fedor/Documents/Coins/BTC/wallets/wallet_btc_testnet:/data/default_wallet
